# Prometheus配置文件
# 用于监控CodeWeave AI工作流平台

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# 规则文件
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # CodeWeave API服务监控
  - job_name: 'codeweave-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL监控 (如果启用了postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis监控 (如果启用了redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Temporal监控
  - job_name: 'temporal'
    static_configs:
      - targets: ['temporal:7233']
    metrics_path: '/metrics'
    scrape_interval: 15s

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 远程写入配置 (可选)
# remote_write:
#   - url: "http://remote-storage:9201/write"

# 远程读取配置 (可选)
# remote_read:
#   - url: "http://remote-storage:9201/read"